set: train
task_type: "VG"   #"VG" or "VQA"
S: "1"
T: 1
target_Q: human
modality_type: "image"
N: 10
Incremental: True
folder_name: "out_engine"

paths:
  train:
    path_label: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB-Reasoning/labels/labels_2d_stitched_new_version/"
    path_image: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/images/image_stitched/"
    path_pano: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/labels_2d_panoptic_stitched_CW_wo5s_test/"
    path_label_3d: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/train_labels/labels_3d/"
    path_pose: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/train_labels/labels_2d_pose_stitched_coco/"
    pcd_file: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/siminpanoptic_3d_full/pointcloud/train_dataset_with_activity/merged_velodyne/"
    bin_file: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/siminpanoptic_3d_full/labels/train_dataset_with_activity/"
    sequences:
       - 'bytes-cafe-2019-02-07_0.json'
       - 'clark-center-2019-02-28_1.json'
       - 'nvidia-aud-2019-04-18_0.json'
#       - 'clark-center-2019-02-28_0.json'
#       - 'clark-center-intersection-2019-02-28_0.json'
#       - 'cubberly-auditorium-2019-04-22_0.json'
#       - 'forbes-cafe-2019-01-22_0.json'
#       - 'gates-159-group-meeting-2019-04-03_0.json'
#       - 'gates-basement-elevators-2019-01-17_1.json'
#       - 'gates-to-clark-2019-02-28_1.json'
#       - 'hewlett-packard-intersection-2019-01-24_0.json'
#       - 'huang-basement-2019-01-25_0.json'
#       - 'huang-lane-2019-02-12_0.json'
#       - 'jordan-hall-2019-04-22_0.json'
#       - 'memorial-court-2019-03-16_0.json'
#       - 'packard-poster-session-2019-03-20_0.json'
#       - 'packard-poster-session-2019-03-20_1.json'
#       - 'packard-poster-session-2019-03-20_2.json'
#       - 'stlc-111-2019-04-19_0.json'
#       - 'svl-meeting-gates-2-2019-04-08_0.json'
#       - 'svl-meeting-gates-2-2019-04-08_1.json'
#       - 'tressider-2019-03-16_0.json'
#       - 'clark-center-2019-02-28_1.json'
#       - 'gates-ai-lab-2019-02-08_0.json'
#       - 'huang-2-2019-01-25_0.json'
#       - 'meyer-green-2019-03-16_0.json'
#       - 'nvidia-aud-2019-04-18_0.json'
#       - 'tressider-2019-03-16_1.json'
#       - 'tressider-2019-04-26_2.json'

  test:
    path_label: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB-Reasoning/labels/labels_2d_stitched_test_new_version1/"
    path_image: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/Test_images/image_stitched/"
    path_pano: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/labels_2d_panoptic_stitched_CW_with5s_test/"
    path_label_3d: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/test_labes/labels_3d/"
    path_pose: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/test_labes/pose_stitched/"
    pcd_file: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/siminpanoptic_3d_full/pointcloud/test_dataset_without_labels/merged_velodyne/"
    bin_file: "/Users/sjah0003/PycharmProjects/pythonProject_visulizastion/JRDB2022/siminpanoptic_3d_full/labels/test_dataset_without_labels/"
    sequences:
#       - 'gates-to-clark-2019-02-28_0.json'
#       - 'hewlett-class-2019-01-23_0.json'
#       - 'cubberly-auditorium-2019-04-22_1.json'
#       - 'discovery-walk-2019-02-28_0.json'
#       - 'discovery-walk-2019-02-28_1.json'
##       - 'food-trucks-2019-02-12_0.json' problem
#       - 'gates-ai-lab-2019-04-17_0.json'
#       - 'gates-basement-elevators-2019-01-17_0.json'
#       - 'gates-foyer-2019-01-17_0.json'
#       - 'hewlett-class-2019-01-23_1.json'
       - 'huang-2-2019-01-25_1.json'
       - 'huang-intersection-2019-01-22_0.json'
       - 'indoor-coupa-cafe-2019-02-06_0.json'
#       - 'lomita-serra-intersection-2019-01-30_0.json'
#       - 'meyer-green-2019-03-16_1.json'
#       - 'nvidia-aud-2019-01-25_0.json'
#       - 'nvidia-aud-2019-04-18_1.json'
#       - 'nvidia-aud-2019-04-18_2.json'
#       - 'outdoor-coupa-cafe-2019-02-06_0.json'
#       - 'quarry-road-2019-02-28_0.json'
#       - 'serra-street-2019-01-30_0.json'
#       - 'stlc-111-2019-04-19_1.json'
#       - 'stlc-111-2019-04-19_2.json'
#       - 'tressider-2019-03-16_2.json'
#       - 'tressider-2019-04-26_0.json'
#       - 'tressider-2019-04-26_1.json'
#       - 'tressider-2019-04-26_3.json'
